name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: influxdata/telegraf
          fetch-depth: 1
          path: telegraf
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - run: ls -lh
      - run: bash build.sh telegraf custom-tags.txt
      - run: ls -lh telegraf/telegraf
