name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
            image: "ubuntu:latest"
          - arch: none
            distro: none
            image: "ubuntu:latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: influxdata/telegraf
          fetch-depth: 1
          path: telegraf
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          base_image: ${{ matrix.image }}
          env: "ARCH: ${{ matrix.arch }}"
          run: |
            uname -rm
            env
            pwd
            ls -lh
