name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
          - arch: none
            distro: none
            base_image: "ubuntu:latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: influxdata/telegraf
          fetch-depth: 1
          path: telegraf
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          setup: mkdir -p artifacts
          dockerRunArgs: --volume "${PWD}/artifacts:/artifacts"
          run: |
            uname -rm >> /artifacts/env
            pwd >> /artifacts/env
            ls -lh >> /artifacts/env
      - run: |
          ls -lh artifacts
          cat artifacts/env
